### ISSUE TITLE
Cannot filter results by reference taxonomy terms

### ISSUE THREAD

**Issue by marijane** [NLightenGroup/nlighten-ontology#76] opened 2018-02-07 22:29 UTC
At the institutional search page, https://alaska.dev.eagle-i.net:8443/institution/, you can only filter by educational research types.

Should also be able to filter by:
* Clinical Research competencies
* Training level
* Audience type (not a reference taxonomy, but should still be a filterable facet)

**Comment by skcheng** [comment] 2018-02-08 16:56
This is not a bug. eagle-i search is by design to allow filtering only on the resource _type_ only.  Displaying filters for properties of the different resources in the left navigation is not helpful with a wide range of resource types, i.e. we would have needed filters for technique (ref tax) but that filter only makes sense in the context of an instrument.
We have since seen the utility of having a more guided/custom search for specific resource types, https://search.eagle-i.net/central/iPSCellSearch.html. This is out of scope for N-Lighten 1.0, but is a possibility for a 2.0.

**Closed as completed by skcheng** 2018-02-08 16:56 UTC
Labels: bug, not an issue
