### ISSUE TITLE
'Creator' dropdown not working for all educational resource types (video and course)

### ISSUE THREAD

**Issue by pitviper6** [NLightenGroup/nlighten-ontology#28] opened 2017-12-11 16:39 UTC
During the creation or editing of an educational resource (video or course), the dropdown for the field 'Creator' does not work - if you try to click on it you get the grayed out circle/slash tooltip (which isn't on the screenshot b/c of grab being stupid, but you can see that it is greyed out). 

When I got back to view the record after finishing my edit, the "university of Juliane" appears as both provider AND creator, so....that's interesting.

![creatordrop](https://user-images.githubusercontent.com/15837566/33842156-b9531a72-de67-11e7-82fa-7e639f86409e.jpeg)
![dropdown2](https://user-images.githubusercontent.com/15837566/33842695-e2001260-de60-11e7-8dec-034e79773ddd.jpeg)

**Comment by skcheng** [comment] 2017-12-11 17:04
@pitviper6 This looks like the same question as #23 ... yes?

**Comment by nicolevasilevsky** [comment] 2017-12-11 21:56
yes, similar issue

**Comment by marijane** [comment] 2017-12-12 21:41
Since Juliane is out, I am going to close this as a duplicate of #23.

**Closed as completed by marijane** 2017-12-12 21:41 UTC
Labels: duplicate
