### ISSUE TITLE
has depth has no choices

### ISSUE THREAD

**Issue by nicolevasilevsky** [NLightenGroup/nlighten-ontology#50] opened 2017-12-14 00:29 UTC
there are not any terms in the has depth field.

Also, I'm not sure what has depth means?

**Comment by nicolevasilevsky** [comment] 2017-12-14 00:53
same with has format

**Comment by marijane** [comment] 2017-12-14 07:50
This is a bug I've been meaning to file.  The drop-down box gets drawn in the wrong place.  Scroll up after clicking and I bet you will find it.

**Comment by skcheng** [comment] 2017-12-14 18:02
This is a known bug with the application. It wasn't prioritized because it was hard to reproduce and didn't happen that often. I'm not sure why it's being so rampant now. For expediency & sanity sake, I'm disinclined to address known bugs, unless otherwise directed.

**Comment by nicolevasilevsky** [comment] 2017-12-14 18:20
Oh yeah, you are right @marijane.
@skcheng- fine with me if you want to make known bugs a lower priority. :)

**Comment by marijane** [comment] 2017-12-15 19:28
I've tagged this as wontfix and I'm going to close it.  That said, my gut says it might need to be, because the behavior is pretty consistent on the NLighten instance.

**Closed as completed by marijane** 2017-12-15 19:28 UTC
Labels: bug, wontfix
